//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppShlist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public int id_shlist_fk { get; set; }
        public int quantity { get; set; }
    
        public virtual ShoppingList ShoppingList { get; set; }
    }
}
